# Generated by Django 6.0.1 on 2026-01-08 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testes.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='TestePromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_nome', models.CharField(max_length=120)),
                ('colaborador_re', models.CharField(max_length=30)),
                ('funcao_em_teste', models.CharField(max_length=120)),
                ('data_inicio', models.DateField()),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('PROMOVER', 'Promover'), ('CANCELAR', 'Cancelar'), ('FINALIZADO', 'Finalizado')], default='EM_ANDAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('anexo_folha_teste', models.FileField(blank=True, null=True, upload_to='folhas_teste/')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testes.loja')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testes.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='PremioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_premio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('data_pagamento', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='testes.testepromocao')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teste', 'numero_premio'), name='uniq_numero_premio_por_teste')],
            },
        ),
    ]
