# Generated by Django 6.0.1 on 2026-01-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'verbose_name': 'Região', 'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisores'},
        ),
        migrations.AlterModelOptions(
            name='testepromocao',
            options={'verbose_name': 'Teste de promoção', 'verbose_name_plural': 'Testes de promoção'},
        ),
    ]
