# Generated by Django 6.0.1 on 2026-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0002_alter_loja_options_alter_regiao_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supervisor',
            new_name='Solicitante',
        ),
        migrations.AlterModelOptions(
            name='premiopago',
            options={'ordering': ['numero_premio']},
        ),
        migrations.AlterModelOptions(
            name='solicitante',
            options={},
        ),
        migrations.RenameField(
            model_name='testepromocao',
            old_name='supervisor',
            new_name='solicitante',
        ),
    ]
