# Generated by Django 6.0.1 on 2026-01-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_rename_supervisor_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testepromocao',
            name='data_cancelado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testepromocao',
            name='data_promovido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testepromocao',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('PROMOVER', 'Promovido'), ('CANCELAR', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
