# Generated by Django 6.0.1 on 2026-01-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0004_testepromocao_data_cancelado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testepromocao',
            name='funcao_em_teste',
        ),
        migrations.AddField(
            model_name='testepromocao',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testes', to='testes.funcao'),
        ),
    ]
