# Generated by Django 6.0.1 on 2026-01-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0005_funcao_remove_testepromocao_funcao_em_teste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testepromocao',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('PROMOVER', 'Promovido'), ('CANCELAR', 'Cancelado')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
