# Generated by Django 6.0.1 on 2026-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0007_alter_funcao_options_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testepromocao',
            name='obs_cancelamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testepromocao',
            name='obs_promocao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
