# Generated by Django 6.0.1 on 2026-01-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0008_testepromocao_obs_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiopago',
            name='observacao',
            field=models.CharField(max_length=255),
        ),
    ]
