# Generated by Django 6.0.1 on 2026-01-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0009_alter_premiopago_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='testes.loja')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.AddField(
            model_name='testepromocao',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testes', to='testes.colaborador'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['loja', 'ativo'], name='testes_cola_loja_id_ae5e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['nome'], name='testes_cola_nome_aeb118_idx'),
        ),
    ]
