# Generated by Django 6.0.1 on 2026-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0010_colaborador_testepromocao_colaborador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
