# Generated by Django 6.0.1 on 2026-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0011_loja_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
